#develop branch configuration
-
  version: '0.1.{build}'
  image: Visual Studio 2017
  before_build:
  - cmd: nuget restore
  build:
    verbosity: minimal
    publish_nuget: true
    publish_nuget_symbols: true
  branches:
    only:
    - develop
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}-alpha'
  configuration: Debug

#master branch configuration
-
  version: '0.1.{build}'
  image: Visual Studio 2017
  before_build:
  - cmd: nuget restore
  build:
    verbosity: minimal
    publish_nuget: true
    publish_nuget_symbols: true
  branches:
    only:
    - master
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}-beta'

  configuration: Release
  artifacts:
  - path: src\Neat.CQRSLite.Contract.Nuget\bin\Debug\Neat.CQRSLite.Contract.*.nupkg
    name: Nuget Package
  - path: src\Neat.CQRSLite.CQRS.Nuget\bin\Debug\Neat.CQRSLite.CQRS.*.nupkg
    name: Nuget Package