#develop branch configuration
-
  version: '0.1.{build}-alpha'
  image: Visual Studio 2017
  before_build:
  - cmd: nuget restore
  build:
    verbosity: minimal
    publish_nuget: true
    publish_nuget_symbols: true
  branches:
    only:
    - develop
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '0.1.{build}'
    assembly_file_version: '0.1.{build}'
    assembly_informational_version: '{version}'
  configuration: Debug
  deploy:
    provider: NuGet
    # empty server: to push to NuGet.org
    api_key:
      secure: jl3WOrWorSRN4TGAiTXHTOKcejnYpO7akTQXKfT6BxqpGLrGb9p4ecu12g1C8iCO
    skip_symbols: false
    # empty symbol_server: to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/

#master branch configuration
-
  version: '0.1.{build}-beta'
  image: Visual Studio 2017
  before_build:
  - cmd: nuget restore
  build:
    verbosity: minimal
    publish_nuget: true
    publish_nuget_symbols: true
  branches:
    only:
    - master
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '0.1.{build}'
    assembly_file_version: '0.1.{build}'
    assembly_informational_version: '{version}'
  configuration: Release
  deploy:
    provider: NuGet
    # empty server: to push to NuGet.org
    api_key:
      secure: jl3WOrWorSRN4TGAiTXHTOKcejnYpO7akTQXKfT6BxqpGLrGb9p4ecu12g1C8iCO
    skip_symbols: false
    # empty symbol_server: to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/